/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.parity.analysis;

import ensp.parity.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAApairPp(AApairPp node);
    void caseABpairPp(ABpairPp node);
    void caseAEmptyPp(AEmptyPp node);
    void caseAAimpairIp(AAimpairIp node);
    void caseABimpairIp(ABimpairIp node);

    void caseTA(TA node);
    void caseTB(TB node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
