/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.parity.analysis;

import java.util.*;
import ensp.parity.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAApairPp(AApairPp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABpairPp(ABpairPp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEmptyPp(AEmptyPp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAimpairIp(AAimpairIp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABimpairIp(ABimpairIp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTA(TA node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTB(TB node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
