/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.parity.node;

import ensp.parity.analysis.*;

@SuppressWarnings("nls")
public final class AApairPp extends PPp
{
    private TA _a_;
    private PIp _ip_;

    public AApairPp()
    {
        // Constructor
    }

    public AApairPp(
        @SuppressWarnings("hiding") TA _a_,
        @SuppressWarnings("hiding") PIp _ip_)
    {
        // Constructor
        setA(_a_);

        setIp(_ip_);

    }

    @Override
    public Object clone()
    {
        return new AApairPp(
            cloneNode(this._a_),
            cloneNode(this._ip_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAApairPp(this);
    }

    public TA getA()
    {
        return this._a_;
    }

    public void setA(TA node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public PIp getIp()
    {
        return this._ip_;
    }

    public void setIp(PIp node)
    {
        if(this._ip_ != null)
        {
            this._ip_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ip_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._a_)
            + toString(this._ip_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._ip_ == child)
        {
            this._ip_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._a_ == oldChild)
        {
            setA((TA) newChild);
            return;
        }

        if(this._ip_ == oldChild)
        {
            setIp((PIp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
