/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.parity.node;

import ensp.parity.analysis.*;

@SuppressWarnings("nls")
public final class ABimpairIp extends PIp
{
    private TB _b_;
    private PIp _ip_;

    public ABimpairIp()
    {
        // Constructor
    }

    public ABimpairIp(
        @SuppressWarnings("hiding") TB _b_,
        @SuppressWarnings("hiding") PIp _ip_)
    {
        // Constructor
        setB(_b_);

        setIp(_ip_);

    }

    @Override
    public Object clone()
    {
        return new ABimpairIp(
            cloneNode(this._b_),
            cloneNode(this._ip_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABimpairIp(this);
    }

    public TB getB()
    {
        return this._b_;
    }

    public void setB(TB node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    public PIp getIp()
    {
        return this._ip_;
    }

    public void setIp(PIp node)
    {
        if(this._ip_ != null)
        {
            this._ip_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ip_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._b_)
            + toString(this._ip_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        if(this._ip_ == child)
        {
            this._ip_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._b_ == oldChild)
        {
            setB((TB) newChild);
            return;
        }

        if(this._ip_ == oldChild)
        {
            setIp((PIp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
