/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.parity.node;

import ensp.parity.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyPp extends PPp
{

    public AEmptyPp()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyPp();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyPp(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
