/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.automate.node;

import ensp.automate.analysis.*;

@SuppressWarnings("nls")
public final class TAba extends Token
{
    public TAba(String text)
    {
        setText(text);
    }

    public TAba(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAba(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAba(this);
    }
}
