/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.automate.node;

import ensp.automate.analysis.*;

@SuppressWarnings("nls")
public final class TEntier extends Token
{
    public TEntier(String text)
    {
        setText(text);
    }

    public TEntier(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEntier(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEntier(this);
    }
}
