/* This file was generated by SableCC (http://www.sablecc.org/). */

package ensp.automate.analysis;

import ensp.automate.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTAba(TAba node);
    void caseTParite(TParite node);
    void caseTEntier(TEntier node);
    void caseTFloat(TFloat node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
